---
- name: Setup server
  hosts: all
  tags: setup
  roles:
    - install-common-deps
    - docker-compose
    - python37

- name: Setup app
  hosts: all
  tags: app
  roles:
    - app
  vars:
      # TODO: Replace with your own git repository
    - git_repo: 'git@github.com:shy2net/nestjs-angular-starter.git'
    - app_dir: '~/app'
