# Install most common dependencies
---

- name: Install git
  yum: name=git state=latest
  become: yes

# - name: Install dependencies for Python 2.7
#   yum:
#     name:
#       - scl-utils
#       - centos-release-scl-rh
#     state: present
#   become: yes

# - name: Install Python 2.7
#   yum:
#     name:
#       - python27
#     state: present
#   become: yes

# - name: Install Python 2.7 Pip
#   shell: |
#     curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o /tmp/get-pip.py
#     python /tmp/get-pip.py
#   become: yes

- name: Update yum
  yum:
    name: '*'
    state: latest
  become: yes

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest
  become: yes

- name: Install Python 3
  yum:
    name:
      - python3
      - python3-pip
    state: present
  become: yes

- name: Install docker module for Python
  pip:
    executable: pip3
    name:
      - docker
      - docker-compose
    state: present
  become: yes

