# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test
          MONGO_INITDB_DATABASE: admin
        ports:
          - 27019:27017
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run install:all
        # Forces mongo-memory-server to be installed
      - run: npm install mongodb-memory-server
      - run: npm test
      - run: npm run ng:test:ci
      - uses: ashley-taylor/junit-report-annotations-action@1.3
        if: always()
        with:
            access-token: ${{ secrets.GITHUB_TOKEN }}
